import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import AppProviders from "@/AppProviders";
import React from "react";

const inter = Inter({
  subsets: ["latin"],
  // variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en dark">
      <body className={cn(inter.className, "dark")}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
